import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: NextRequest) {
  try {
    const { text, name, jobTitle } = await request.json();

    if (!text) {
      return NextResponse.json({ error: "No text provided" }, { status: 400 });
    }

    // Create a new PDFDocument
    const pdfDoc = await PDFDocument.create();
    const timesRomanFont = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const timesRomanBoldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Add a blank page to the document
    let page = pdfDoc.addPage([595.28, 841.89]); // A4 size
    const { width, height } = page.getSize();
    const margin = 50;
    let yPosition = height - margin;

    // Helper to add text and handle page breaks
    const addText = (txt: string, size: number, font: any, color = rgb(0, 0, 0)) => {
      const lines = txt.split('\n');
      for (const line of lines) {
        // Simple word wrap
        const words = line.split(' ');
        let currentLine = '';
        
        for (const word of words) {
          const testLine = currentLine + (currentLine ? ' ' : '') + word;
          const lineWidth = font.widthOfTextAtSize(testLine, size);
          
          if (lineWidth > width - 2 * margin) {
            page.drawText(currentLine, { x: margin, y: yPosition, size, font, color });
            yPosition -= size + 5;
            currentLine = word;
            
            if (yPosition < margin) {
              page = pdfDoc.addPage([595.28, 841.89]);
              yPosition = height - margin;
            }
          } else {
            currentLine = testLine;
          }
        }
        
        if (currentLine) {
          page.drawText(currentLine, { x: margin, y: yPosition, size, font, color });
          yPosition -= size + 5;
        } else {
          yPosition -= size + 5; // Empty line
        }

        if (yPosition < margin) {
          page = pdfDoc.addPage([595.28, 841.89]);
          yPosition = height - margin;
        }
      }
    };

    // Header
    if (name) {
      const nameUpper = name.toUpperCase();
      const nameWidth = timesRomanBoldFont.widthOfTextAtSize(nameUpper, 24);
      page.drawText(nameUpper, { 
        x: (width - nameWidth) / 2, 
        y: yPosition, 
        size: 24, 
        font: timesRomanBoldFont 
      });
      yPosition -= 30;
    }

    const brandText = 'TAILORED RESUME GENERATED BY BROSKIE.AI';
    const brandWidth = timesRomanFont.widthOfTextAtSize(brandText, 10);
    page.drawText(brandText, { 
      x: (width - brandWidth) / 2, 
      y: yPosition, 
      size: 10, 
      font: timesRomanFont,
      color: rgb(0.37, 0.36, 0.9) // #5E5CE6 equivalent
    });
    yPosition -= 40;

    // Body
    addText(text, 11, timesRomanFont);

    // Serialize the PDFDocument to bytes (a Uint8Array)
    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="Tailored_Resume_${name || 'Candidate'}.pdf"`
      }
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json({ error: "Failed to generate PDF: " + (error as any).message }, { status: 500 });
  }
}
