import { NextRequest, NextResponse } from "next/server";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

export async function POST(request: NextRequest) {
  try {
    const { text, name, jobTitle } = await request.json();

    if (!text) {
      return NextResponse.json({ error: "No text provided" }, { status: 400 });
    }

    // Create a new PDFDocument
    const pdfDoc = await PDFDocument.create();
    const helvetica = await pdfDoc.embedFont(StandardFonts.Helvetica);
    const helveticaBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

    // Add a blank page to the document
    let page = pdfDoc.addPage([595.28, 841.89]); // A4 size
    const { width, height } = page.getSize();
    const margin = 50;
    const maxWidth = width - 2 * margin;
    let yPosition = height - margin;

    const addNewPage = () => {
      page = pdfDoc.addPage([595.28, 841.89]);
      yPosition = height - margin;
    };

    // Helper to wrap and draw text
    const drawWrappedText = (txt: string, size: number, font: any, color = rgb(0.1, 0.1, 0.1), indent = 0) => {
      const words = txt.split(' ');
      let currentLine = '';
      
      for (const word of words) {
        const testLine = currentLine + (currentLine ? ' ' : '') + word;
        const lineWidth = font.widthOfTextAtSize(testLine, size);
        
        if (lineWidth > maxWidth - indent) {
          if (yPosition < margin + 20) addNewPage();
          page.drawText(currentLine, { x: margin + indent, y: yPosition, size, font, color });
          yPosition -= size + 4;
          currentLine = word;
        } else {
          currentLine = testLine;
        }
      }
      
      if (currentLine) {
        if (yPosition < margin + 20) addNewPage();
        page.drawText(currentLine, { x: margin + indent, y: yPosition, size, font, color });
        yPosition -= size + 4;
      }
    };

    const drawSectionHeader = (title: string) => {
      yPosition -= 15;
      if (yPosition < margin + 40) addNewPage();
      
      const headerText = title.toUpperCase();
      page.drawText(headerText, {
        x: margin,
        y: yPosition,
        size: 13,
        font: helveticaBold,
        color: rgb(0, 0, 0)
      });
      
      yPosition -= 4;
      page.drawLine({
        start: { x: margin, y: yPosition },
        end: { x: width - margin, y: yPosition },
        thickness: 1,
        color: rgb(0.7, 0.7, 0.7)
      });
      
      yPosition -= 16;
    };

    // Header Implementation
    if (name) {
      const nameUpper = name.toUpperCase();
      page.drawText(nameUpper, { 
        x: margin, 
        y: yPosition, 
        size: 22, 
        font: helveticaBold,
        color: rgb(0, 0, 0)
      });
      yPosition -= 25;
    }

    if (jobTitle) {
      page.drawText(jobTitle, {
        x: margin,
        y: yPosition,
        size: 12,
        font: helvetica,
        color: rgb(0.37, 0.36, 0.9) // #5E5CE6 Indigo
      });
      yPosition -= 30;
    } else {
      yPosition -= 10;
    }

    // Parse text and render sections
    const lines = text.split('\n');
    let isFirstLine = true;

    for (const line of lines) {
      const trimmed = line.trim();
      if (!trimmed) {
        yPosition -= 8;
        continue;
      }

      // Detection for headers (All caps or common headers)
      const commonHeaders = [
        'SUMMARY', 'PROFESSIONAL SUMMARY', 'EXPERIENCE', 'WORK EXPERIENCE', 
        'PROJECTS', 'EDUCATION', 'SKILLS', 'TECHNICAL SKILLS', 'CERTIFICATIONS',
        'AWARDS', 'LANGUAGES', 'CONTACT'
      ];
      
      const isLikelyHeader = (trimmed.length < 40 && (
        trimmed === trimmed.toUpperCase() || 
        commonHeaders.some(h => trimmed.toUpperCase().startsWith(h))
      ));

      if (isLikelyHeader) {
        drawSectionHeader(trimmed);
      } else if (trimmed.startsWith('*') || trimmed.startsWith('-') || trimmed.startsWith('•')) {
        // Bullet point
        const bulletContent = trimmed.replace(/^[\*\-•]\s*/, '');
        drawWrappedText('• ' + bulletContent, 10, helvetica, rgb(0.2, 0.2, 0.2), 10);
      } else {
        drawWrappedText(trimmed, 10, helvetica, rgb(0.2, 0.2, 0.2));
      }
      
      yPosition -= 4;
    }

    // Add subtle footer
    const pages = pdfDoc.getPages();
    pages.forEach((p, idx) => {
      const footerText = `Generated by Broskie.ai | Page ${idx + 1} of ${pages.length}`;
      const footerSize = 8;
      const footerWidth = helvetica.widthOfTextAtSize(footerText, footerSize);
      p.drawText(footerText, {
        x: (width - footerWidth) / 2,
        y: 20,
        size: footerSize,
        font: helvetica,
        color: rgb(0.6, 0.6, 0.6)
      });
    });

    // Serialize to bytes
    const pdfBytes = await pdfDoc.save();

    return new NextResponse(Buffer.from(pdfBytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `inline; filename="Tailored_Resume_${name || 'Candidate'}.pdf"`
      }
    });
  } catch (error) {
    console.error("PDF generation error:", error);
    return NextResponse.json({ error: "Failed to generate PDF: " + (error as any).message }, { status: 500 });
  }
}
